server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

#spring.security.oauth2.jwk.rsaPublicKey: classpath:public.key
#spring.security.oauth2.jwk.rsaPrivateKey: classpath:private.key

#spring.security.oauth2.jwk.keystore-location: classpath:keystore.p12
#spring.security.oauth2.jwk.store-password: password
